#!/bin/sh
rm /var/tmp/temporary_pkg-plist 2>/dev/null
rm /var/tmp/temporary_pkg-plist-fixed 2>/dev/null
cp ../pkg-plist /var/tmp/temporary_pkg-plist

echo "adjusting pkg-plist"

cat /var/tmp/temporary_pkg-plist | \
sed \
-e 's#^\/you\/have\/to\/check\/what\/makeplist\/gives\/you##' \
-e '/^$/d' \
-e 's#^\%\%PORTDOCS\%\%##g' \
> /var/tmp/temporary_pkg-plist-fixed
cp /var/tmp/temporary_pkg-plist-fixed ../pkg-plist
